### ISSUE TITLE
RSA võtmetega testkaardiga signeerimine ebaõnnestub

### ISSUE THREAD

**Issue by nostneji** [open-eid/jdigidoc-hwcrypto-demo#1]
Võtsime käesoleva projekti koodi oma test-juhtumite sekka, et kontrollida, kas see töötab ECDSA võtmetega testkaartidega. Peab tõdema, et seal meil probleeme ei tekkinud.

Kui aga püüdsime testida vana **RSA võtmetega testkaardiga**, siis tekkisid probleemid.

Stsenaarium oli järgmine:
1a) kasutaja avab rakenduse ja valib faili;
1b) kasutaja vajutab 'Sign' nupule;
2) rakendus kuvab sertifikaadi valikut;
3) kasutaja valib sertifikaadi;
4) rakendus küsib PIN2 koodi;
5) kasutaja sisestab PIN2 koodi;
6) rakendus EI muuda veebilehte, konsooli logisse ei tule veateateid - allkirjastatud konteinerit alla laadida ei saa;
7) kasutaja kordab samme (1b)-(5);
8) rakendus kuvab lehele lisaks 'Download' sektsiooni;
9) kasutaja vajutab nupule 'Download' ja salvestab allkirjastatud bdoc-faili.

Saadud bdoc-failis on 2 signatuuri, mõlemad ilma OCSP token'ita.

Rakenduse logis on näha järgmiseid ridu:

2017-09-28 11:55:56.612 DEBUG 49208 --- [http-nio-8090-exec-4] e.s.h.demo.controller.SigningController  : Generating hash from cert 308204FE30...
2017-09-28 11:56:05.550 DEBUG 49208 --- [http-nio-8090-exec-6] e.s.h.demo.controller.SigningController  : Creating container for signature 400EEAC3E5...
2017-09-28 11:56:05.552 ERROR 49208 --- [http-nio-8090-exec-6] e.s.h.demo.controller.SigningController  : Error signing container: 65ee.sk.digidoc.DigiDocException; nested exception is:
        ERROR: 65 - Missing CA cert for ocsp request

Testimise konfiguratsioon:

- Windows 7 (64-bit)
- IE 11, Ver: 11.0.9600.18762CO, UpdVer: 11.0.45
- ie-token-signing_3.13.0.3009_x86
- minidriver-3.12.0.77.x64

**Comment by andresrosenthal** [comment]
_ERROR: 65 - Missing CA cert for ocsp request_

See viga tuleneb sellest, et JDigiDoc pole konfigureeritud antud RSA testkaardi väljastaja sertifikaadiga.
Ma olin eelnevalt lisanud hulk live serte ning test sertidest ainult ECDSA testkaardi väljastaja ning OCSP serdid. Ma nüüd lisasin portsu test serte juurde.

Kui ikka saab sama viga, siis on võimalik väljasta serte JDigiDoci lisada kui panna sert **src/main/resources/certs** kausta ning vastavalt konffida see **src/main/resources/jdigidoc.cfg** failis

**Comment by naare** [comment]
Juhin tähelepanu ka sellele, et teenuse üles seadmisel tuleb seadistada ka vastavad usaldusteenused millele kasutatavad test serdid vastaksid.
